wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: huggingface
    huggingface_version: 2.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1658135749
    t:
      1:
      - 1
      - 5
      - 11
      - 53
      - 55
      4: 3.7.13
      5: 0.12.17
      6: 2.5.1
      8:
      - 5
